---
- name: Restart app
  become_user: azureuser
  shell: |
    source ~/.nvm/nvm.sh
    cd /home/azureuser/theepicbook
    pm2 restart epicbook || pm2 start server.js --name epicbook
  args:
    executable: /bin/bash
